name: lint and test
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.1'
      - name: install dependencies
        run : |
          go version
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.37.1
      - name: Run vet & lint
        run: |
          go vet .
          golangci-lint run --out-format checkstyle > golangci-lint-report.xml || true
      - name: Run testing
        run: go test --race -v